library(DESeq2)
countData_rg <- read.csv('projects_limgroup/gab/2025/mutagenesis_pool/regex/df_e1_rg_deseq2.csv',header=TRUE, sep = ",")
metaData <- read.csv('projects_limgroup/gab/2025/mutagenesis_pool/mx3c_deseq2/mut_metadata.txt', header = TRUE, sep = "\t")
dds <- DESeqDataSetFromMatrix(countData=countData_rg,colData=metaData,design=~pop, tidy = TRUE)
res14 <- results(dds, contrast=c("pop", "p1", "p4"), independentFiltering=TRUE, alpha=0.05, pAdjustMethod="BH", parallel=TRUE)
res24 <- results(dds, contrast=c("pop", "p2", "p4"), independentFiltering=TRUE, alpha=0.05, pAdjustMethod="BH", parallel=TRUE)
res34 <- results(dds, contrast=c("pop", "p3", "p4"), independentFiltering=TRUE, alpha=0.05, pAdjustMethod="BH", parallel=TRUE)
write.csv(res14, file = "res14.csv", row.names = TRUE)
write.csv(res24, file = "res24.csv", row.names = TRUE)
write.csv(res34, file = "res34.csv", row.names = TRUE)